// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axzvrywxslleycttmabd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4enZyeXd4c2xsZXljdHRtYWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Mzk2NTEsImV4cCI6MjA1OTAxNTY1MX0.S7f_yearHZ24nm6n55uCRwGSH9hyTDdwBvtCJwu2fn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);